/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Sistema;
import javax.swing.JOptionPane;

/**
 *
 * @author ramom
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mPessoas = new javax.swing.JMenuItem();
        mCafe = new javax.swing.JMenuItem();
        mSalas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mConsultaCafeEsala = new javax.swing.JMenuItem();
        mConsultaPessoa = new javax.swing.JMenuItem();
        mConsultaGeral = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Gerar Programação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Aperte apenas após a criação de todas as");

        jLabel2.setText("Apenas uma vez!");

        jLabel3.setText(" salas, salas de café e pessoas.");

        jMenu1.setText("Cadastros");

        mPessoas.setText("Pessoas");
        mPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPessoasActionPerformed(evt);
            }
        });
        jMenu1.add(mPessoas);

        mCafe.setText("Café");
        mCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCafeActionPerformed(evt);
            }
        });
        jMenu1.add(mCafe);

        mSalas.setText("Salas");
        mSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalasActionPerformed(evt);
            }
        });
        jMenu1.add(mSalas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultar");

        mConsultaCafeEsala.setText("Cafés");
        mConsultaCafeEsala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaCafeEsalaActionPerformed(evt);
            }
        });
        jMenu2.add(mConsultaCafeEsala);

        mConsultaPessoa.setText("Pessoa");
        mConsultaPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaPessoaActionPerformed(evt);
            }
        });
        jMenu2.add(mConsultaPessoa);

        mConsultaGeral.setText("Salas");
        mConsultaGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mConsultaGeralActionPerformed(evt);
            }
        });
        jMenu2.add(mConsultaGeral);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 85, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(81, 81, 81))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(129, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(382, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPessoasActionPerformed
        cadastroPessoas tela = new cadastroPessoas();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_mPessoasActionPerformed

    private void mCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCafeActionPerformed
       cadastroSalaCafe tela = new cadastroSalaCafe();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_mCafeActionPerformed

    private void mSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalasActionPerformed
       cadastroSala tela = new cadastroSala();
       tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_mSalasActionPerformed

    private void mConsultaCafeEsalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaCafeEsalaActionPerformed
       consultaSalaEventoCafe tela = new consultaSalaEventoCafe();
       tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_mConsultaCafeEsalaActionPerformed

    private void mConsultaPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaPessoaActionPerformed
       consultaPessoa tela = new consultaPessoa();
       tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_mConsultaPessoaActionPerformed

    private void mConsultaGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultaGeralActionPerformed
       consultaGeral tela = new consultaGeral();
       tela.setVisible(true);
       dispose();
    }//GEN-LAST:event_mConsultaGeralActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Sistema sistema = new Sistema();
        sistema.etapa2();
        sistema.intervalo1();
        sistema.intervalo2();
        JOptionPane.showMessageDialog(null, "Programação realizada!");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mCafe;
    private javax.swing.JMenuItem mConsultaCafeEsala;
    private javax.swing.JMenuItem mConsultaGeral;
    private javax.swing.JMenuItem mConsultaPessoa;
    private javax.swing.JMenuItem mPessoas;
    private javax.swing.JMenuItem mSalas;
    // End of variables declaration//GEN-END:variables
}
